<?php

namespace Benson\LaravelFirebird\Tests;

use Benson\LaravelFirebird\FirebirdConnection;
use Illuminate\Database\Schema\Blueprint;
use PHPUnit\Framework\Attributes\Test;
use RuntimeException;

class SchemaGrammarTest extends TestCase
{
    #[Test]
    public function it_creates_identity_columns_on_firebird_three_and_newer()
    {
        $connection = $this->makeConnection(['server_version' => '5.0.3']);

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
        });

        $this->assertCount(1, $statements);
        $this->assertSame(
            'create table "foo_users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR(255) NOT NULL)',
            $statements[0]
        );
    }

    #[Test]
    public function it_creates_legacy_generators_on_servers_without_identity_columns()
    {
        $connection = $this->makeConnection(['server_version' => '2.5.9']);

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
        });

        $this->assertCount(4, $statements);
        $this->assertSame(
            'create table "foo_users" ("id" INTEGER PRIMARY KEY, "name" VARCHAR(255) NOT NULL)',
            $statements[0]
        );
        $this->assertStringContainsString('create generator "foo_users_id_gen"', $statements[1]);
        $this->assertSame('set generator "foo_users_id_gen" to 0', $statements[2]);
        $this->assertStringContainsString('CREATE TRIGGER "foo_users_id_bi"', $statements[3]);
    }

    #[Test]
    public function it_keeps_legacy_generators_for_dialect_one_connections()
    {
        $connection = $this->makeConnection([
            'server_version' => '5.0.3',
            'dialect' => '1',
            'quote_identifiers' => false,
            'uppercase_identifiers' => true,
        ]);

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) {
            $table->increments('id');
        });

        $this->assertCount(4, $statements);
        $this->assertStringNotContainsString('IDENTITY', $statements[0]);
    }

    #[Test]
    public function it_hashes_index_names_beyond_the_identifier_limit()
    {
        $connection = $this->makeConnection(['server_version' => '3.0.10']);

        $longIndex = 'foo_users_with_a_very_long_table_name_email_unique';

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) use ($longIndex) {
            $table->string('email');
            $table->unique('email', $longIndex);
        });

        preg_match('/ADD CONSTRAINT "([^"]+)"/', $statements[1], $matches);

        $this->assertSame(31, strlen($matches[1]));
        $this->assertStringStartsWith('foo_users_with_a_very_', $matches[1]);

        // The drop side must resolve to the same constrained name.
        $blueprint = new Blueprint($connection, 'foo_users', function (Blueprint $table) use ($longIndex) {
            $table->dropUnique($longIndex);
        });

        $this->assertStringContainsString('DROP CONSTRAINT "'.$matches[1].'"', $blueprint->toSql()[0]);
    }

    #[Test]
    public function it_allows_longer_identifiers_on_firebird_four_and_newer()
    {
        $connection = $this->makeConnection(['server_version' => '4.0.4']);

        $longIndex = 'foo_users_with_a_very_long_table_name_email_unique';

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) use ($longIndex) {
            $table->string('email');
            $table->unique('email', $longIndex);
        });

        $this->assertStringContainsString('ADD CONSTRAINT "'.$longIndex.'"', $statements[1]);
    }

    protected function createTableSql(FirebirdConnection $connection, string $table, callable $callback): array
    {
        $blueprint = new Blueprint($connection, $table, function (Blueprint $table) use ($callback) {
            $table->create();

            $callback($table);
        });

        return $blueprint->toSql();
    }

    protected function makeConnection(array $config = [])
    {
        $connection = new FirebirdConnection(
            fn () => throw new RuntimeException('The schema grammar tests must not connect to Firebird.'),
            '',
            '',
            $config
        );

        $connection->useDefaultSchemaGrammar();

        return $connection;
    }
}
