<?php

namespace Benson\LaravelFirebird\Tests;

use Benson\LaravelFirebird\FirebirdConnection;
use Illuminate\Database\Schema\Blueprint;
use PHPUnit\Framework\Attributes\Test;
use RuntimeException;

class SchemaGrammarTest extends TestCase
{
    #[Test]
    public function it_creates_identity_columns_on_firebird_three_and_newer()
    {
        $connection = $this->makeConnection(['server_version' => '5.0.3']);

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
        });

        $this->assertCount(1, $statements);
        $this->assertSame(
            'create table "foo_users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "name" VARCHAR(255) NOT NULL)',
            $statements[0]
        );
    }

    #[Test]
    public function it_creates_legacy_generators_on_servers_without_identity_columns()
    {
        $connection = $this->makeConnection(['server_version' => '2.5.9']);

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
        });

        $this->assertCount(4, $statements);
        $this->assertSame(
            'create table "foo_users" ("id" INTEGER PRIMARY KEY, "name" VARCHAR(255) NOT NULL)',
            $statements[0]
        );
        $this->assertStringContainsString('create generator "foo_users_id_gen"', $statements[1]);
        $this->assertSame('set generator "foo_users_id_gen" to 0', $statements[2]);
        $this->assertStringContainsString('CREATE TRIGGER "foo_users_id_bi"', $statements[3]);
    }

    #[Test]
    public function it_keeps_legacy_generators_for_dialect_one_connections()
    {
        $connection = $this->makeConnection([
            'server_version' => '5.0.3',
            'dialect' => '1',
            'quote_identifiers' => false,
            'uppercase_identifiers' => true,
        ]);

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) {
            $table->increments('id');
        });

        $this->assertCount(4, $statements);
        $this->assertStringNotContainsString('IDENTITY', $statements[0]);
    }

    #[Test]
    public function it_hashes_index_names_beyond_the_identifier_limit()
    {
        $connection = $this->makeConnection(['server_version' => '3.0.10']);

        $longIndex = 'foo_users_with_a_very_long_table_name_email_unique';

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) use ($longIndex) {
            $table->string('email');
            $table->unique('email', $longIndex);
        });

        preg_match('/ADD CONSTRAINT "([^"]+)"/', $statements[1], $matches);

        $this->assertSame(31, strlen($matches[1]));
        $this->assertStringStartsWith('foo_users_with_a_very_', $matches[1]);

        // The drop side must resolve to the same constrained name.
        $blueprint = new Blueprint($connection, 'foo_users', function (Blueprint $table) use ($longIndex) {
            $table->dropUnique($longIndex);
        });

        $this->assertStringContainsString('DROP CONSTRAINT "'.$matches[1].'"', $blueprint->toSql()[0]);
    }

    #[Test]
    public function it_allows_longer_identifiers_on_firebird_four_and_newer()
    {
        $connection = $this->makeConnection(['server_version' => '4.0.4']);

        $longIndex = 'foo_users_with_a_very_long_table_name_email_unique';

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) use ($longIndex) {
            $table->string('email');
            $table->unique('email', $longIndex);
        });

        $this->assertStringContainsString('ADD CONSTRAINT "'.$longIndex.'"', $statements[1]);
    }

    #[Test]
    public function it_uses_time_zone_types_on_firebird_four_and_newer()
    {
        $modern = $this->makeConnection(['server_version' => '4.0.4']);

        $statements = $this->createTableSql($modern, 'foo_events', function (Blueprint $table) {
            $table->timestampTz('happened_at');
            $table->timeTz('happened_time');
            $table->dateTimeTz('logged_at');
        });

        $this->assertStringContainsString('"happened_at" TIMESTAMP WITH TIME ZONE', $statements[0]);
        $this->assertStringContainsString('"happened_time" TIME WITH TIME ZONE', $statements[0]);
        $this->assertStringContainsString('"logged_at" TIMESTAMP WITH TIME ZONE', $statements[0]);

        $legacy = $this->makeConnection(['server_version' => '3.0.10']);

        $statements = $this->createTableSql($legacy, 'foo_events', function (Blueprint $table) {
            $table->timestampTz('happened_at');
            $table->timeTz('happened_time');
        });

        $this->assertStringContainsString('"happened_at" TIMESTAMP', $statements[0]);
        $this->assertStringNotContainsString('WITH TIME ZONE', $statements[0]);
    }

    #[Test]
    public function it_changes_nullability_through_alter_column_on_firebird_three_and_newer()
    {
        $connection = $this->makeConnection(['server_version' => '3.0.10']);

        $blueprint = new Blueprint($connection, 'foo_users', function (Blueprint $table) {
            $table->string('name', 50)->nullable()->change();
        });

        $this->assertContains('ALTER TABLE "foo_users" ALTER "name" DROP NOT NULL', $blueprint->toSql());
    }

    #[Test]
    public function it_changes_nullability_through_the_system_table_on_legacy_servers()
    {
        $connection = $this->makeConnection(['server_version' => '2.5.9']);

        $blueprint = new Blueprint($connection, 'foo_users', function (Blueprint $table) {
            $table->string('name', 50)->change();
        });

        $this->assertContains(
            "update rdb\$relation_fields set rdb\$null_flag = 1 where rdb\$relation_name = 'foo_users' and rdb\$field_name = 'name'",
            $blueprint->toSql()
        );
    }

    #[Test]
    public function it_compiles_table_and_column_comments()
    {
        $connection = $this->makeConnection(['server_version' => '5.0.3']);

        $statements = $this->createTableSql($connection, 'foo_users', function (Blueprint $table) {
            $table->comment("User's table");
            $table->string('name')->comment('Full name');
        });

        $this->assertContains('comment on column "foo_users"."name" is \'Full name\'', $statements);
        $this->assertContains('comment on table "foo_users" is \'User\'\'s table\'', $statements);
    }

    #[Test]
    public function it_applies_custom_index_name_templates()
    {
        $connection = $this->makeConnection([
            'server_version' => '5.0.3',
            'index_names' => [
                'primary' => 'pk_{table}',
                'unique' => 'uq_{table}_{columns}',
                'index' => 'ix_{table}_{columns}',
                'foreign' => 'fk_{table}_{columns}',
            ],
        ]);

        $blueprint = new \Benson\LaravelFirebird\Schema\Blueprint($connection, 'clientes', function (\Benson\LaravelFirebird\Schema\Blueprint $table) {
            $table->primary('id');
            $table->unique('email');
            $table->index('nome');
            $table->foreign('user_id')->references('id')->on('users');
        });

        $sql = implode(' ; ', $blueprint->toSql());

        $this->assertStringContainsString('ADD CONSTRAINT "pk_clientes" PRIMARY KEY', $sql);
        $this->assertStringContainsString('ADD CONSTRAINT "uq_clientes_email" UNIQUE', $sql);
        $this->assertStringContainsString('CREATE INDEX "ix_clientes_nome"', $sql);
        $this->assertStringContainsString('ADD CONSTRAINT "fk_clientes_user_id"', $sql);
    }

    #[Test]
    public function it_compiles_a_unique_index_without_a_constraint()
    {
        $connection = $this->makeConnection([
            'server_version' => '5.0.3',
            'index_names' => ['uniqueIndex' => 'UX_{table}_{columns}'],
        ]);

        $blueprint = new \Benson\LaravelFirebird\Schema\Blueprint($connection, 'clientes', function (\Benson\LaravelFirebird\Schema\Blueprint $table) {
            $table->uniqueIndex('email');
            $table->uniqueIndex(['cpf', 'nome'], 'UX_EXPLICITO');
        });

        $sql = $blueprint->toSql();

        $this->assertContains('CREATE UNIQUE INDEX "UX_clientes_email" ON "clientes" ("email")', $sql);
        $this->assertContains('CREATE UNIQUE INDEX "UX_EXPLICITO" ON "clientes" ("cpf", "nome")', $sql);
    }

    #[Test]
    public function it_drops_a_unique_index_by_name_and_by_columns()
    {
        $connection = $this->makeConnection([
            'server_version' => '5.0.3',
            'index_names' => ['uniqueIndex' => 'UX_{table}_{columns}'],
        ]);

        $blueprint = new \Benson\LaravelFirebird\Schema\Blueprint($connection, 'clientes', function (\Benson\LaravelFirebird\Schema\Blueprint $table) {
            $table->dropUniqueIndex('UX_clientes_email');
            $table->dropUniqueIndex(['email']);
        });

        $sql = $blueprint->toSql();

        $this->assertSame([
            'DROP INDEX "UX_clientes_email"',
            'DROP INDEX "UX_clientes_email"',
        ], $sql);
    }

    #[Test]
    public function it_keeps_the_framework_default_index_names_without_templates()
    {
        $connection = $this->makeConnection(['server_version' => '5.0.3']);

        $blueprint = new \Benson\LaravelFirebird\Schema\Blueprint($connection, 'clientes', function (\Benson\LaravelFirebird\Schema\Blueprint $table) {
            $table->unique('email');
        });

        $this->assertStringContainsString('"clientes_email_unique"', implode(' ; ', $blueprint->toSql()));
    }

    #[Test]
    public function the_schema_builder_uses_the_firebird_blueprint()
    {
        $connection = $this->makeConnection(['server_version' => '5.0.3']);

        $builder = $connection->getSchemaBuilder();
        $method = new \ReflectionMethod($builder, 'createBlueprint');
        $blueprint = $method->invoke($builder, 'clientes', null);

        $this->assertInstanceOf(\Benson\LaravelFirebird\Schema\Blueprint::class, $blueprint);
    }

    protected function createTableSql(FirebirdConnection $connection, string $table, callable $callback): array
    {
        $blueprint = new Blueprint($connection, $table, function (Blueprint $table) use ($callback) {
            $table->create();

            $callback($table);
        });

        return $blueprint->toSql();
    }

    protected function makeConnection(array $config = [])
    {
        $connection = new FirebirdConnection(
            fn () => throw new RuntimeException('The schema grammar tests must not connect to Firebird.'),
            '',
            '',
            $config
        );

        $connection->useDefaultSchemaGrammar();

        return $connection;
    }
}
